name: github-jwt-generator.yml

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            
            const id_token = await core.getIDToken()
            //const id_token = await core.getIDToken(audience)

            fs.writeFileSync('jwt', id_token)

      - uses: actions/upload-artifact@v3
        with:
          name: jwt
          path: jwt
            
